services:
  por-client-demo:
    # build: .
    image: primuslabs/por-client-demo:v0.1.0
    container_name: por-client-demo
    volumes:
      - ./.config.yml:/app/.config.yml:ro
      - ./request_data:/app/request_data
      - ./.cache:/app/.cache
    restart: always
